# Starship Configuration
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Timeout for commands (in milliseconds)
command_timeout = 1000

# Format: define the order and style of the prompt
format = """
[┌─](bold purple)\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$nodejs\
$python\
$rust\
$golang\
$java\
$php\
$docker_context\
$line_break\
[└─](bold purple)\
$character"""

# Username
[username]
show_always = true
style_user = "bold purple"
style_root = "bold red"
format = "[$user]($style) "

# Hostname
[hostname]
ssh_only = false
style = "bold cyan"
format = "[@$hostname]($style) "
disabled = true  # Set to false if you want to see hostname

# Directory
[directory]
style = "bold pink"
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 3
truncate_to_repo = true
read_only = " 󰌾"

# Git Branch
[git_branch]
symbol = " "
style = "bold yellow"
format = "[$symbol$branch]($style) "

# Git Status
[git_status]
style = "bold red"
format = '([\[$all_status$ahead_behind\]]($style) )'
conflicted = "🏳"
up_to_date = ""
untracked = "?"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = "$"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"
disabled = false

# Character (prompt symbol)
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
vimcmd_symbol = "[⬅](bold green)"

# Node.js
[nodejs]
symbol = " "
style = "bold green"
format = "[$symbol($version )]($style)"

# Python
[python]
symbol = " "
style = "bold yellow"
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
pyenv_version_name = false
detect_extensions = ['py']
detect_files = ['.python-version', 'Pipfile', '__pycache__', 'pyproject.toml', 'requirements.txt', 'setup.py', 'tox.ini']

# Rust
[rust]
symbol = " "
style = "bold red"
format = "[$symbol($version )]($style)"

# Go
[golang]
symbol = " "
style = "bold cyan"
format = "[$symbol($version )]($style)"

# Java
[java]
symbol = " "
style = "bold red"
format = "[$symbol($version )]($style)"

# PHP
[php]
symbol = " "
style = "bold purple"
format = "[$symbol($version )]($style)"

# Docker
[docker_context]
symbol = " "
style = "bold blue"
format = "[$symbol$context]($style) "
only_with_files = true

# Time (optional - disabled by default)
[time]
disabled = true
time_format = "%T"
style = "bold white"
format = '[ $time]($style) '

# Line break
[line_break]
disabled = false

# Package version
[package]
symbol = " "
style = "bold cyan"
format = "[$symbol$version]($style) "
disabled = false

# Battery
[battery]
full_symbol = "🔋"
charging_symbol = "⚡"
discharging_symbol = "💀"
disabled = true

[[battery.display]]
threshold = 30
style = "bold red"

# Memory usage
[memory_usage]
disabled = true
threshold = 75
symbol = " "
style = "bold dimmed white"
format = "$symbol[$ram_pct]($style) "

# Command duration
[cmd_duration]
min_time = 500
style = "bold yellow"
format = "[took [$duration]($style)]"

# AWS
[aws]
symbol = "  "
disabled = true

# Conda
[conda]
symbol = " "
style = "bold green"
format = "[$symbol$environment]($style) "
